# http configuration

# logger configuration
log:
  level: 'info'
  format: 'json'
  prefix: 'Framework-test'
  director: 'storage/log'
  linkName: 'latest_log'
  showLine: false
  encodeLevel: 'LowercaseColorLevelEncoder'
  stacktraceKey: 'stacktrace'
  logInConsole: false