// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"project_cli/pkg"
)

// Injectors from wire.go:

func InitService() *pkg.Pkg {
	pkgPkg := pkg.InitPkg()
	return pkgPkg
}
